[tool.poetry]
name = "fatscraperbot"
version = "0.1.0"
description = ""
authors = ["Nik <nik@ndeast.com>"]

[tool.poetry.dependencies]
python = "^3.8"
python-telegram-bot = "^12.7"
pylint = "^2.5.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
